version: '2'

services:
  browser_transmitter:
    container_name: browser_transmitter
    build: .
    environment:
      KAFKA_URL: 'kafka:29092'
      KAFKA_TOPIC: 'frames'
    networks: 
      - default
      - server_network
    ports:
      - 5000:5000

networks:
  server_network:
    external: true
